name: local
variables:
  - name: customer_token
    value: ""
  - name: provider_token
    value: ""
  - name: service_id
    value: "1"
  - name: reservation_id
    value: "1"
  - name: notification_id
    value: "1"
  - name: tag_id
    value: "1"
  - name: reservation_start_time
    value: ""
